version: "3.8"
services:
  nmcli:
    build: .
    network_mode: "host"
    volumes:
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    cap_add:
      - NET_ADMIN
    ports:
    - "5000:5000"
    stdin_open: true
    tty: true